// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/api/products/app/product/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/api/products/app/product/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/products/app/product/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/perfil/[userId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/perfil/[userId]">> = Specific
  const handler = {} as typeof import("../../../app/app/perfil/[userId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/perfil/editar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/perfil/editar">> = Specific
  const handler = {} as typeof import("../../../app/app/perfil/editar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/auth/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/login">> = Specific
  const handler = {} as typeof import("../../../app/auth/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/auth/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/register">> = Specific
  const handler = {} as typeof import("../../../app/auth/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/kyc/mock/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kyc/mock">> = Specific
  const handler = {} as typeof import("../../../app/kyc/mock/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/kyc/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kyc">> = Specific
  const handler = {} as typeof import("../../../app/kyc/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/perfil/editar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/perfil/editar">> = Specific
  const handler = {} as typeof import("../../../app/perfil/editar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/product/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/product/[id]">> = Specific
  const handler = {} as typeof import("../../../app/product/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/user/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/user/[id]">> = Specific
  const handler = {} as typeof import("../../../app/user/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/app/api/user/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/app/api/user">> = Specific
  const handler = {} as typeof import("../../../app/api/app/api/user/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cron/liberar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/liberar">> = Specific
  const handler = {} as typeof import("../../../app/api/cron/liberar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/kyc/start/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/kyc/start">> = Specific
  const handler = {} as typeof import("../../../app/api/kyc/start/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/kyc/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/kyc/status">> = Specific
  const handler = {} as typeof import("../../../app/api/kyc/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/kyc/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/kyc/webhook">> = Specific
  const handler = {} as typeof import("../../../app/api/kyc/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/offers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/offers">> = Specific
  const handler = {} as typeof import("../../../app/api/offers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/payments/app/api/payments/confirm-delivery/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/app/api/payments/confirm-delivery">> = Specific
  const handler = {} as typeof import("../../../app/api/payments/app/api/payments/confirm-delivery/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/payments/app/api/payments/mock/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/app/api/payments/mock">> = Specific
  const handler = {} as typeof import("../../../app/api/payments/app/api/payments/mock/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/payments/confirm-delivery/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/confirm-delivery">> = Specific
  const handler = {} as typeof import("../../../app/api/payments/confirm-delivery/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/payments/confirm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/confirm">> = Specific
  const handler = {} as typeof import("../../../app/api/payments/confirm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/payments/mock/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/mock">> = Specific
  const handler = {} as typeof import("../../../app/api/payments/mock/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/payments/start/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/start">> = Specific
  const handler = {} as typeof import("../../../app/api/payments/start/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/products/app/api/products/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/app/api/products">> = Specific
  const handler = {} as typeof import("../../../app/api/products/app/api/products/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/products/app/api/reviews/[userId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/app/api/reviews/[userId]">> = Specific
  const handler = {} as typeof import("../../../app/api/products/app/api/reviews/[userId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/products/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products">> = Specific
  const handler = {} as typeof import("../../../app/api/products/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/reviews/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reviews">> = Specific
  const handler = {} as typeof import("../../../app/api/reviews/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/user/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user">> = Specific
  const handler = {} as typeof import("../../../app/api/user/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/users/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/users/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/api/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/app/api/upload">> = Specific
  const handler = {} as typeof import("../../../app/app/api/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
